# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 437)
        MainWindow.setIconSize(QtCore.QSize(60, 60))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(680, 10, 141, 16))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(680, 50, 141, 16))
        self.comboBox_2.setObjectName("comboBox_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(550, 10, 101, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(550, 50, 101, 21))
        self.textEdit.setObjectName("textEdit")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(680, 90, 141, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 3, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(550, 90, 104, 21))
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 270, 271, 111))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(50, 70, 361, 201))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_8 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_8.setGeometry(QtCore.QRect(20, 50, 91, 31))
        self.textEdit_8.setObjectName("textEdit_8")
        self.textEdit_9 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.textEdit_10 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_10.setGeometry(QtCore.QRect(20, 110, 91, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.tcno = QtWidgets.QTextEdit(self.groupBox)
        self.tcno.setGeometry(QtCore.QRect(140, 50, 121, 31))
        self.tcno.setObjectName("tcno")
        self.isim = QtWidgets.QTextEdit(self.groupBox)
        self.isim.setGeometry(QtCore.QRect(140, 80, 121, 31))
        self.isim.setObjectName("isim")
        self.soyisim = QtWidgets.QTextEdit(self.groupBox)
        self.soyisim.setGeometry(QtCore.QRect(140, 110, 121, 31))
        self.soyisim.setObjectName("soyisim")
        self.textEdit_11 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_11.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.cinsiyet = QtWidgets.QTextEdit(self.groupBox)
        self.cinsiyet.setGeometry(QtCore.QRect(140, 140, 121, 31))
        self.cinsiyet.setObjectName("cinsiyet")
        self.textEdit_4 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_4.setGeometry(QtCore.QRect(20, 170, 91, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.dogum = QtWidgets.QDateEdit(self.groupBox)
        self.dogum.setGeometry(QtCore.QRect(140, 170, 121, 31))
        self.dogum.setObjectName("dogum")
        self.saatler = QtWidgets.QGroupBox(self.centralwidget)
        self.saatler.setGeometry(QtCore.QRect(560, 130, 291, 141))
        self.saatler.setObjectName("saatler")
        self.radioButton = QtWidgets.QRadioButton(self.saatler)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 81, 21))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 40, 95, 21))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 60, 95, 21))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 80, 95, 21))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 100, 95, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_6.setGeometry(QtCore.QRect(90, 20, 95, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_7.setGeometry(QtCore.QRect(90, 40, 95, 20))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_8.setGeometry(QtCore.QRect(90, 60, 95, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_9.setGeometry(QtCore.QRect(90, 80, 95, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_10.setGeometry(QtCore.QRect(90, 100, 95, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_11.setGeometry(QtCore.QRect(190, 20, 95, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_12.setGeometry(QtCore.QRect(190, 40, 95, 20))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_13.setGeometry(QtCore.QRect(190, 60, 95, 20))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_14.setGeometry(QtCore.QRect(190, 80, 95, 20))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.saatler)
        self.radioButton_15.setGeometry(QtCore.QRect(190, 100, 95, 20))
        self.radioButton_15.setObjectName("radioButton_15")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 251, 21))
        self.label.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label.setObjectName("label")
        self.randevuButton = QtWidgets.QPushButton(self.centralwidget)
        self.randevuButton.setGeometry(QtCore.QRect(190, 300, 221, 71))
        self.randevuButton.setObjectName("randevuButton")
        self.bolumsec = QtWidgets.QComboBox(self.centralwidget)
        self.bolumsec.setGeometry(QtCore.QRect(60, 320, 91, 22))
        self.bolumsec.setObjectName("bolumsec")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MHRS"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">Klinik</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">Doktor</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt; font-weight:600; font-style:italic;\">Randevu Tarihi</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "ONAYLA"))
        self.groupBox.setTitle(_translate("MainWindow", "Hasta Bilgileri"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TC Kimlik No:</p></body></html>"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Adı:</p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Soyadı:</p></body></html>"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cinsiyet:</p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">D.Tarihi:</span></p></body></html>"))
        self.saatler.setTitle(_translate("MainWindow", "Saat"))
        self.radioButton.setText(_translate("MainWindow", "9.00"))
        self.radioButton_2.setText(_translate("MainWindow", "9.30"))
        self.radioButton_3.setText(_translate("MainWindow", "10.00"))
        self.radioButton_4.setText(_translate("MainWindow", "10.30"))
        self.radioButton_5.setText(_translate("MainWindow", "11.00"))
        self.radioButton_6.setText(_translate("MainWindow", "11.30"))
        self.radioButton_7.setText(_translate("MainWindow", "12.00"))
        self.radioButton_8.setText(_translate("MainWindow", "14.00"))
        self.radioButton_9.setText(_translate("MainWindow", "14.30"))
        self.radioButton_10.setText(_translate("MainWindow", "15.00"))
        self.radioButton_11.setText(_translate("MainWindow", "15.30"))
        self.radioButton_12.setText(_translate("MainWindow", "16.00"))
        self.radioButton_13.setText(_translate("MainWindow", "16.30"))
        self.radioButton_14.setText(_translate("MainWindow", "17.00"))
        self.radioButton_15.setText(_translate("MainWindow", "17.30"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">ADANA ŞEHİR HASTANESİ </span></p></body></html>"))
        self.randevuButton.setText(_translate("MainWindow", "Randevuları Listele"))
